### ISSUE TITLE
dose not work for some reason (1.19.3)

### ISSUE THREAD

**Issue by Esc2020** [JustS-js/debugStickSurvival#1]
Привет Just :)
При использование палки в выживание, в одиночной игре, майн просто вылетает.
Проверял на чистой новой версии fabric с fabric-api и без других модов, версия игры 1.19.3, вот краш репорт:
[crash-2023-04-16_23.12.06-server.txt](https://github.com/JustS-js/debugStickSurvival/files/11243303/crash-2023-04-16_23.12.06-server.txt)

Когда мод установлен на сервере палку просто невозможно использовать в выиживание.
Крафт палки и там и там работает нормально.

P.S.
Смотрю тебя начиная с МШ2 и очень нравится твой контент, на этот мод наткнулся случайно на modrinth)
С прошедшим ДР тебя

**Comment by JustS-js** [comment]
Я залил мод протестировав только версию 1.19.2
К сожалению, уже буквально в 1.19.3 изменилась структура, которая использовалась мною в коде.
Залью сюда и на modrinth подходящие версии мода для соответствующих версий игры как будет возможность

**Comment by JustS-js** [comment]
Перепроверил все версии с 1.19 до 1.19.4 и обновил всё, что нужно.
Новые версии можно найти тут:
https://modrinth.com/mod/survival-debug-stick
И тут:
https://github.com/JustS-js/debugStickSurvival/releases
