### ISSUE TITLE
will there be a version for Paper servers?

### ISSUE THREAD

**Issue by zhigulevskoe** [JustS-js/debugStickSurvival#10]
ive just wanted to ask: is it possible to make a similar plugin for paper or is this mod made just with the capabilities of fabric api? (our server is on paper, and the plugin that allows you to use the debug stick in survival has not found)

**Comment by JustS-js** [comment]
I never wrote anything for Paper, so not sure about that. But the code for this modification is documented well enough, so if you can find someone to write such plugin - go ahead!
