### ISSUE TITLE
Config is reinforced in creative mode

### ISSUE THREAD

**Issue by arvitus** [JustS-js/debugStickSurvival#13]
Since the latest update, config restrictions are also applied to creative mode but they should only be applied to survival mode.
If you want to go a step further, you could make it a config option or even a permission to set it per player.

Also, I think the "properties" key should not be required when it is empty. `{"id":"iron_bars"}` should be the same as `{"id":"iron_bars","properties":{}}`

**Comment by JustS-js** [comment]
Seems like that bug was introduced with left-click functionality, as i forgot to check if player is in Creative or Survival.
About "properties" keys, that's just a byproduct of converting existing config code to Minecraft's CODEC system. I couldn't figure out how to implement optional keys.

**Comment by arvitus** [comment]
The creative bug doesn't happen on v1.2.0

**Comment by JustS-js** [comment]
i'll look into that

**Comment by JustS-js** [comment]
just had to use `optionalFieldOf()` instead of `fieldOf()`, who could have thought 🤔
Gonna release this fix later, i want to be sure everything works as intended.

**Comment by arvitus** [comment]
thx for looking into it so fast :)

**Comment by JustS-js** [comment]
Tested out, should be working fine in the latest release (1.2.2 for Minecraft 1.21)
