### ISSUE TITLE
Конфиг возвращается в исходное состояние после любого изменения

### ISSUE THREAD

**Issue by LendSpele** [JustS-js/debugStickSurvival#14]
Я менял конфиг для того чтобы запретить менять waterlogged, но после рестарта конфиг вернул к изначальному варианту, я даже вставил конфиг который предлагается в Вики, не помогло

**Comment by JustS-js** [comment]
Либо ваша проблема была исправлена в новых версиях, либо вы неправильно использовали формат конфигурационного файла (.json)
Укажите версию мода и Майнкрафта, которую вы использовали, а так же предоставьте ваш файл конфигурации. Иначе я не смогу оказать вам помощь!

**Comment by JustS-js** [comment]
Если ваша проблема всё ещё не решена, то рекомендую создать новый issue. Этот закрываю в связи с длительным молчанием.
