### ISSUE TITLE
backport updates to 1.19.4

### ISSUE THREAD

**Issue by h3oCharles** [JustS-js/debugStickSurvival#15]
hi, i am limited to playing in 1.19.4 because of a server with multiple mods. As I've seen the changelog, is there a chance that the updates made in later MC versions can also be made for 1.19.4?

**Comment by JustS-js** [comment]
I will consider that

**Comment by JustS-js** [comment]
backported v1.2.2 for Fabric 1.19.3-1.19.4, check new releases
