### ISSUE TITLE
Support 1.21.3

### ISSUE THREAD

**Issue by lesxmore** [JustS-js/debugStickSurvival#17]
Hi, will debugStickSurvival be updated to support version 1.21.3?

**Comment by JustS-js** [comment]
yes

**Comment by JustS-js** [comment]
See [release page](https://github.com/JustS-js/debugStickSurvival/releases/tag/v1.2.2-Fabric-1.21) for mod version 1.2.2, mc 1.21. Added build that is compatible with 1.21.2-1.21.3
