### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Dan1er0** [JustS-js/debugStickSurvival#18]
I dont know where to type this but I have one/two question/s (i dont use github just made an account). So new version of Minecraft just came out and I wanted to play it with the mod on but Its on 1.21.3 and not 1.21.4. So I have kind of request or question. Could you update the mod to 1.21.4 or could I do it myself. (somehow.). Sorry for trouble im not the kind of a guy speeding up other people and I just don`t know or where to ask that. Thanks.

Best Regards.

**Comment by Dan1er0** [comment]
Nevermind. I think I done something VERY dumb and not good for mod but i just changed the one parameter in "fabric-mod.json" to be not for 1.21.2 but for 1.21.4 and It worked! sorry for trouble

**Comment by JustS-js** [comment]
What you did is just changing what version the mod expects to see upon loading. If i am not mistaken, 1.21.4 has not changed any code that is used in debug stick, so no problems should pop out.
If you will encounter any issue, feel free to post about it here. I will update mod files later for people to use mod out of the box.
