### ISSUE TITLE
Interactable Blocks can't be edited

### ISSUE THREAD

**Issue by Vartemys** [JustS-js/debugStickSurvival#3]
Hey there!
First of all, really glad someone made this mod lol.
I also really appreciate the config possibilty.
I've got one issue though: You can't edit interactable blocks (e.g.  fence gates). Wouldn't it be more useful to let the player cycle through options with SNEAK + RIGHT CLICK and edit the selected option with SNEAK + LEFT CLICK?
That way you could easily prevent the player from accidentaly interacting with the block.
Greetings!

**Comment by JustS-js** [comment]
I didn't really think that someone would need to edit interactable blocks like gates or chests, as you don't usually place them in hard-to-access places
But your idea sounds good, i might add this functionality in the 1.20.2 update with possibility to change this in config

**Comment by JustS-js** [comment]
included in 1.1.0 for MC 1.21
