### ISSUE TITLE
Add possibility to forbid exact values of specified property

### ISSUE THREAD

**Issue by DemonSlayer112** [JustS-js/debugStickSurvival#6]
Hi, loving the mod so far, however,
I have a mod adding slabs of all kinds of blocks, and I want to keep the ability to switch from lower to upper and waterlogging.
But...some slabs(Netherite Slab) and all of them can be changed to double, when broken dupes the slab.
Can i disable `Type` from being set to double?

Even if i forbid `Type` it will forbid it for ALL blocks with `Type` state right?
Maybe if we could have control on which state for which block types we can forbid, or just forbid specific values for states like `Double`

**Comment by JustS-js** [comment]
welp, i'm a bit late here, sorry for that
I'll need to check if that is possible, as for now i don't even remember how this works exactly

**Comment by JustS-js** [comment]
Seems like this is not possible in current iteration. Maybe i will add that in a later update, as this is pretty important for any "piece" blocks from other mods

**Comment by JustS-js** [comment]
Included in v1.2.0 for MC 1.21
